apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done"]
      env:
        - name: SSHD_PATH
          valueFrom:
            configMapKeyRef:
              name: ssh-config2
              key: key1
        - name: CONFIG_JSON
          valueFrom: 
            configMapKeyRef:
              name: my-configmap
              key: app.json
      envFrom:
        - configMapRef:
            name: from-env-file
