apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done"]
      env:
        - name: MARIADB_PASS
          valueFrom:
            secretKeyRef:
              name: my-db-pass
              key: root
