apiVersion: v1
kind: Pod
metadata:
  name: init-pod2
  labels:
    kubernetes.io/example: init-pod
spec:
  initContainers:
  - name: prepare
    image: alpine:3.2
    command: ['sh', '-c', 'apk update; apk add git; mkdir /app; git clone -b develop https://github.com/mariano-italiano/lx-k_Feb.git /app']
    volumeMounts:
    - name: sharedvol
      mountPath: /app
  containers:
  - name: nginx
    image: nginx:1.19.2
    volumeMounts:
    - name: sharedvol
      mountPath: /usr/share/nginx/html  
  volumes:
  - name: sharedvol
    emptyDir: {}
