apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mk-test
  name: mk-test
spec:
  containers:
  - image: marcinkujawski/python-api:1.0
    name: mk-test
    readinessProbe:
      httpGet:
        path: /api
        port: 8080
    livenessProbe:
      httpGet:
        path: /api
        port: 8080
      initialDelaySeconds: 5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
