apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-pod
spec:
  nodeSelector:
    kubernetes.io/app: nginx-app
  containers:
  - image: nginx
    name: nodename-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
