apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'touch /tmp/ok; sleep 60; rm /tmp/ok; sleep 1d']
    volumeMounts:
      - name: vol1
        mountPath: /tmp
  - name: nginx
    image: nginx:1.19.2
    volumeMounts:
      - name: vol1
        mountPath: /tmp
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        port: 80
        path: /
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 3
    livenessProbe:
      exec:
        command: 
        - cat
        - /tmp/ok
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
  - name: vol1
    emptyDir: {} 
